# Generated by Django 4.2.2 on 2023-07-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование квиза')),
                ('description', models.TextField(verbose_name='Описание квиза')),
                ('image', models.ImageField(blank=True, upload_to='quizes/image/', verbose_name='изображение')),
                ('duration', models.SmallIntegerField(verbose_name='Время прохождения в минутах')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizes', to='user.department', verbose_name='Направление')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizes', to='quizes.quizlevel', verbose_name='Уровень квиза')),
                ('tags', models.ManyToManyField(blank=True, related_name='quizes', to='quizes.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
            },
        ),
    ]
