# Generated by Django 4.2.2 on 2023-07-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizes.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(verbose_name='Описание квиза'),
        ),
        migrations.AlterField(
            model_name='quizlevel',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание уровня'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='description',
            field=models.TextField(verbose_name='Описание учебного материала'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование учебного материала'),
        ),
    ]
