# Generated by Django 4.2.2 on 2023-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Объяснение'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(verbose_name='правильный ответ'),
        ),
    ]
