# Generated by Django 4.2.2 on 2023-07-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.CharField(blank=True, max_length=240, verbose_name='Объяснение'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(verbose_name='правильный ответ'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.answer', verbose_name='Ответ')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizes.statistic', verbose_name='Статистика квиза')),
            ],
        ),
        migrations.CreateModel(
            name='LastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.question', verbose_name='Вопрос')),
                ('statistic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_question', to='quizes.statistic', verbose_name='Статистика квиза')),
            ],
            options={
                'verbose_name': 'Последний вопрос',
                'verbose_name_plural': 'Последние вопросы',
            },
        ),
    ]
