# Generated by Django 4.2.2 on 2023-07-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_statistic_wrong_answers_answer_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastquestion',
            name='statistic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_question', to='quizes.statistic', verbose_name='Последний отвеченный вопрос'),
        ),
    ]
