# Generated by Django 4.2.2 on 2023-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_assignedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ONE', 'один ответ'), ('MNY', 'нексколько ответов'), ('LST', 'список ответов'), ('OPN', 'открытый ответ')], default='ONE', max_length=3, verbose_name='Тип вопроса'),
        ),
    ]
