# Generated by Django 4.2.2 on 2023-07-24 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='threshold',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Порог прохождения квиза в %'),
        ),
    ]
