# Generated by Django 4.2.2 on 2023-07-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.PositiveIntegerField(verbose_name='Время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='quizes.question', verbose_name='Вопрос')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='quizes.statistic', verbose_name='Статистика квиза')),
            ],
            options={
                'verbose_name': 'Вопрос пользователя',
                'verbose_name_plural': 'Вопросы пользователя',
            },
        ),
    ]
