# Generated by Django 4.2.2 on 2023-07-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_userquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=240, verbose_name='Текст ответа')),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizes.answer', verbose_name='Ответ')),
                ('user_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizes.userquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
    ]
