# Generated by Django 4.2.2 on 2023-07-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers_list', to='quizes.answerlist', verbose_name='Ответ из списка')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers_list', to='quizes.useranswer', verbose_name='Ответ пользователя')),
            ],
            options={
                'verbose_name': 'Ответ пользователя из списка',
                'verbose_name_plural': 'Ответы пользователя из списка',
            },
        ),
    ]
