# Generated by Django 4.2.2 on 2023-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0014_userquestion_is_right'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Статистика прохождения квиза', 'verbose_name_plural': 'Статистика прохождения квизов'},
        ),
        migrations.AddField(
            model_name='statistic',
            name='count_answered',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вопросов отвечено'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='count_questions',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вопросов в квизе'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='count_right',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Правильно вопросов отвечено'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='count_wrong',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Неверно вопросов отвечено'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='Квиз назначен'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Квиз завершен'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_failed',
            field=models.BooleanField(default=False, verbose_name='Квиз провален'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Квиз пройден'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='mod_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='quiz_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время прохождения квиза'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Отвечен верно'),
        ),
    ]
