# Generated by Django 4.2.2 on 2023-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0015_alter_statistic_options_statistic_count_answered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quizes/image/default/', verbose_name='Изображение квиза')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение для квиза',
                'verbose_name_plural': 'Изображения для квизов',
            },
        ),
        migrations.AddField(
            model_name='assignedquiz',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата назначения'),
        ),
    ]
