# Generated by Django 4.2.2 on 2023-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user/avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='score', null=True),
        ),
    ]
